version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-assets11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: asset_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5451:5432"

  backend:
    build: ./Backend
    container_name: backend-assets
    environment:
      PGUSER: postgres
      PGPASSWORD: admin834
      PGHOST: postgres
      PGDATABASE: asset_management
      PGPORT: 5432
    ports:
      - "3051:3051"
    depends_on:
      - postgres

  employee-assets:
    build: ./Employee-Assets
    container_name: employee-assets11
    ports:
      - "8051:80"
    stdin_open: true
    tty: true

  hr-assets:
    build: ./HR-Assets
    container_name: hr-assets11
    ports:
      - "8052:80"
    stdin_open: true
    tty: true

volumes:
  postgres_data:

